// <auto-generated />
using System;
using ApiExchangeBot.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiExchangeBot.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220814181259_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelegramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GetCurrency")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("money");

                    b.Property<int>("SetCurrency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AmountId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ownerTransferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmountId");

                    b.HasIndex("ownerTransferId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.TransferArgument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransferId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.ToTable("Arguments");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Currency", b =>
                {
                    b.HasOne("ApiExchangeBot.Models.EF.Tables.Account", null)
                        .WithMany("Wallet")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Transfer", b =>
                {
                    b.HasOne("ApiExchangeBot.Models.EF.Tables.Currency", "Amount")
                        .WithMany()
                        .HasForeignKey("AmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiExchangeBot.Models.EF.Tables.Account", "ownerTransfer")
                        .WithMany()
                        .HasForeignKey("ownerTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amount");

                    b.Navigation("ownerTransfer");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.TransferArgument", b =>
                {
                    b.HasOne("ApiExchangeBot.Models.EF.Tables.Transfer", null)
                        .WithMany("arguments")
                        .HasForeignKey("TransferId");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Account", b =>
                {
                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ApiExchangeBot.Models.EF.Tables.Transfer", b =>
                {
                    b.Navigation("arguments");
                });
#pragma warning restore 612, 618
        }
    }
}
